//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlueApp.NezamMohandesyWS {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberType", Namespace="http://www.fceo.ir/")]
    public enum MemberType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Temporary = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Permanent = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.fceo.ir/", ConfigurationName="NezamMohandesyWS.AccountingWebServiceSoap")]
    public interface AccountingWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.fceo.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetMemberInfoByCode", ReplyAction="*")]
        GlueApp.NezamMohandesyWS.GetMemberInfoByCodeResponse GetMemberInfoByCode(GlueApp.NezamMohandesyWS.GetMemberInfoByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetMemberInfoByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetMemberInfoByCodeResponse> GetMemberInfoByCodeAsync(GlueApp.NezamMohandesyWS.GetMemberInfoByCodeRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.fceo.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewMembersCode", ReplyAction="*")]
        GlueApp.NezamMohandesyWS.GetNewMembersCodeResponse GetNewMembersCode(GlueApp.NezamMohandesyWS.GetNewMembersCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewMembersCode", ReplyAction="*")]
        System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetNewMembersCodeResponse> GetNewMembersCodeAsync(GlueApp.NezamMohandesyWS.GetNewMembersCodeRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.fceo.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewMembersCodeByType", ReplyAction="*")]
        GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeResponse GetNewMembersCodeByType(GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewMembersCodeByType", ReplyAction="*")]
        System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeResponse> GetNewMembersCodeByTypeAsync(GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.fceo.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetProjectInfo", ReplyAction="*")]
        GlueApp.NezamMohandesyWS.GetProjectInfoResponse GetProjectInfo(GlueApp.NezamMohandesyWS.GetProjectInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetProjectInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetProjectInfoResponse> GetProjectInfoAsync(GlueApp.NezamMohandesyWS.GetProjectInfoRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.fceo.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewProjectsCode", ReplyAction="*")]
        GlueApp.NezamMohandesyWS.GetNewProjectsCodeResponse GetNewProjectsCode(GlueApp.NezamMohandesyWS.GetNewProjectsCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewProjectsCode", ReplyAction="*")]
        System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetNewProjectsCodeResponse> GetNewProjectsCodeAsync(GlueApp.NezamMohandesyWS.GetNewProjectsCodeRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.fceo.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetCoInfoByCode", ReplyAction="*")]
        GlueApp.NezamMohandesyWS.GetCoInfoByCodeResponse GetCoInfoByCode(GlueApp.NezamMohandesyWS.GetCoInfoByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetCoInfoByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetCoInfoByCodeResponse> GetCoInfoByCodeAsync(GlueApp.NezamMohandesyWS.GetCoInfoByCodeRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.fceo.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewCoCode", ReplyAction="*")]
        GlueApp.NezamMohandesyWS.GetNewCoCodeResponse GetNewCoCode(GlueApp.NezamMohandesyWS.GetNewCoCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewCoCode", ReplyAction="*")]
        System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetNewCoCodeResponse> GetNewCoCodeAsync(GlueApp.NezamMohandesyWS.GetNewCoCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberInfoByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberInfoByCode", Namespace="http://www.fceo.ir/", Order=0)]
        public GlueApp.NezamMohandesyWS.GetMemberInfoByCodeRequestBody Body;
        
        public GetMemberInfoByCodeRequest() {
        }
        
        public GetMemberInfoByCodeRequest(GlueApp.NezamMohandesyWS.GetMemberInfoByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetMemberInfoByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public GlueApp.NezamMohandesyWS.MemberType MemberType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PassWord;
        
        public GetMemberInfoByCodeRequestBody() {
        }
        
        public GetMemberInfoByCodeRequestBody(int MeId, GlueApp.NezamMohandesyWS.MemberType MemberType, string UserName, string PassWord) {
            this.MeId = MeId;
            this.MemberType = MemberType;
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberInfoByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberInfoByCodeResponse", Namespace="http://www.fceo.ir/", Order=0)]
        public GlueApp.NezamMohandesyWS.GetMemberInfoByCodeResponseBody Body;
        
        public GetMemberInfoByCodeResponse() {
        }
        
        public GetMemberInfoByCodeResponse(GlueApp.NezamMohandesyWS.GetMemberInfoByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetMemberInfoByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMemberInfoByCodeResult;
        
        public GetMemberInfoByCodeResponseBody() {
        }
        
        public GetMemberInfoByCodeResponseBody(string GetMemberInfoByCodeResult) {
            this.GetMemberInfoByCodeResult = GetMemberInfoByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewMembersCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewMembersCode", Namespace="http://www.fceo.ir/", Order=0)]
        public GlueApp.NezamMohandesyWS.GetNewMembersCodeRequestBody Body;
        
        public GetNewMembersCodeRequest() {
        }
        
        public GetNewMembersCodeRequest(GlueApp.NezamMohandesyWS.GetNewMembersCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewMembersCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        public GetNewMembersCodeRequestBody() {
        }
        
        public GetNewMembersCodeRequestBody(int MeId, string UserName, string PassWord) {
            this.MeId = MeId;
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewMembersCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewMembersCodeResponse", Namespace="http://www.fceo.ir/", Order=0)]
        public GlueApp.NezamMohandesyWS.GetNewMembersCodeResponseBody Body;
        
        public GetNewMembersCodeResponse() {
        }
        
        public GetNewMembersCodeResponse(GlueApp.NezamMohandesyWS.GetNewMembersCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewMembersCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNewMembersCodeResult;
        
        public GetNewMembersCodeResponseBody() {
        }
        
        public GetNewMembersCodeResponseBody(string GetNewMembersCodeResult) {
            this.GetNewMembersCodeResult = GetNewMembersCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewMembersCodeByTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewMembersCodeByType", Namespace="http://www.fceo.ir/", Order=0)]
        public GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeRequestBody Body;
        
        public GetNewMembersCodeByTypeRequest() {
        }
        
        public GetNewMembersCodeByTypeRequest(GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewMembersCodeByTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public GlueApp.NezamMohandesyWS.MemberType MemberType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PassWord;
        
        public GetNewMembersCodeByTypeRequestBody() {
        }
        
        public GetNewMembersCodeByTypeRequestBody(int MeId, GlueApp.NezamMohandesyWS.MemberType MemberType, string UserName, string PassWord) {
            this.MeId = MeId;
            this.MemberType = MemberType;
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewMembersCodeByTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewMembersCodeByTypeResponse", Namespace="http://www.fceo.ir/", Order=0)]
        public GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeResponseBody Body;
        
        public GetNewMembersCodeByTypeResponse() {
        }
        
        public GetNewMembersCodeByTypeResponse(GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewMembersCodeByTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNewMembersCodeByTypeResult;
        
        public GetNewMembersCodeByTypeResponseBody() {
        }
        
        public GetNewMembersCodeByTypeResponseBody(string GetNewMembersCodeByTypeResult) {
            this.GetNewMembersCodeByTypeResult = GetNewMembersCodeByTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectInfo", Namespace="http://www.fceo.ir/", Order=0)]
        public GlueApp.NezamMohandesyWS.GetProjectInfoRequestBody Body;
        
        public GetProjectInfoRequest() {
        }
        
        public GetProjectInfoRequest(GlueApp.NezamMohandesyWS.GetProjectInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetProjectInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProjectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        public GetProjectInfoRequestBody() {
        }
        
        public GetProjectInfoRequestBody(int ProjectId, string UserName, string PassWord) {
            this.ProjectId = ProjectId;
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectInfoResponse", Namespace="http://www.fceo.ir/", Order=0)]
        public GlueApp.NezamMohandesyWS.GetProjectInfoResponseBody Body;
        
        public GetProjectInfoResponse() {
        }
        
        public GetProjectInfoResponse(GlueApp.NezamMohandesyWS.GetProjectInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetProjectInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetProjectInfoResult;
        
        public GetProjectInfoResponseBody() {
        }
        
        public GetProjectInfoResponseBody(string GetProjectInfoResult) {
            this.GetProjectInfoResult = GetProjectInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewProjectsCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewProjectsCode", Namespace="http://www.fceo.ir/", Order=0)]
        public GlueApp.NezamMohandesyWS.GetNewProjectsCodeRequestBody Body;
        
        public GetNewProjectsCodeRequest() {
        }
        
        public GetNewProjectsCodeRequest(GlueApp.NezamMohandesyWS.GetNewProjectsCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewProjectsCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProjectCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int AgentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PassWord;
        
        public GetNewProjectsCodeRequestBody() {
        }
        
        public GetNewProjectsCodeRequestBody(int ProjectCode, int AgentId, string UserName, string PassWord) {
            this.ProjectCode = ProjectCode;
            this.AgentId = AgentId;
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewProjectsCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewProjectsCodeResponse", Namespace="http://www.fceo.ir/", Order=0)]
        public GlueApp.NezamMohandesyWS.GetNewProjectsCodeResponseBody Body;
        
        public GetNewProjectsCodeResponse() {
        }
        
        public GetNewProjectsCodeResponse(GlueApp.NezamMohandesyWS.GetNewProjectsCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewProjectsCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNewProjectsCodeResult;
        
        public GetNewProjectsCodeResponseBody() {
        }
        
        public GetNewProjectsCodeResponseBody(string GetNewProjectsCodeResult) {
            this.GetNewProjectsCodeResult = GetNewProjectsCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCoInfoByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCoInfoByCode", Namespace="http://www.fceo.ir/", Order=0)]
        public GlueApp.NezamMohandesyWS.GetCoInfoByCodeRequestBody Body;
        
        public GetCoInfoByCodeRequest() {
        }
        
        public GetCoInfoByCodeRequest(GlueApp.NezamMohandesyWS.GetCoInfoByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetCoInfoByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int OfficeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        public GetCoInfoByCodeRequestBody() {
        }
        
        public GetCoInfoByCodeRequestBody(int OfficeId, string UserName, string PassWord) {
            this.OfficeId = OfficeId;
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCoInfoByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCoInfoByCodeResponse", Namespace="http://www.fceo.ir/", Order=0)]
        public GlueApp.NezamMohandesyWS.GetCoInfoByCodeResponseBody Body;
        
        public GetCoInfoByCodeResponse() {
        }
        
        public GetCoInfoByCodeResponse(GlueApp.NezamMohandesyWS.GetCoInfoByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetCoInfoByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCoInfoByCodeResult;
        
        public GetCoInfoByCodeResponseBody() {
        }
        
        public GetCoInfoByCodeResponseBody(string GetCoInfoByCodeResult) {
            this.GetCoInfoByCodeResult = GetCoInfoByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewCoCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewCoCode", Namespace="http://www.fceo.ir/", Order=0)]
        public GlueApp.NezamMohandesyWS.GetNewCoCodeRequestBody Body;
        
        public GetNewCoCodeRequest() {
        }
        
        public GetNewCoCodeRequest(GlueApp.NezamMohandesyWS.GetNewCoCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewCoCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int OfficeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        public GetNewCoCodeRequestBody() {
        }
        
        public GetNewCoCodeRequestBody(int OfficeId, string UserName, string PassWord) {
            this.OfficeId = OfficeId;
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewCoCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewCoCodeResponse", Namespace="http://www.fceo.ir/", Order=0)]
        public GlueApp.NezamMohandesyWS.GetNewCoCodeResponseBody Body;
        
        public GetNewCoCodeResponse() {
        }
        
        public GetNewCoCodeResponse(GlueApp.NezamMohandesyWS.GetNewCoCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewCoCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNewCoCodeResult;
        
        public GetNewCoCodeResponseBody() {
        }
        
        public GetNewCoCodeResponseBody(string GetNewCoCodeResult) {
            this.GetNewCoCodeResult = GetNewCoCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountingWebServiceSoapChannel : GlueApp.NezamMohandesyWS.AccountingWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountingWebServiceSoapClient : System.ServiceModel.ClientBase<GlueApp.NezamMohandesyWS.AccountingWebServiceSoap>, GlueApp.NezamMohandesyWS.AccountingWebServiceSoap {
        
        public AccountingWebServiceSoapClient() {
        }
        
        public AccountingWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountingWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlueApp.NezamMohandesyWS.GetMemberInfoByCodeResponse GlueApp.NezamMohandesyWS.AccountingWebServiceSoap.GetMemberInfoByCode(GlueApp.NezamMohandesyWS.GetMemberInfoByCodeRequest request) {
            return base.Channel.GetMemberInfoByCode(request);
        }
        
        public string GetMemberInfoByCode(int MeId, GlueApp.NezamMohandesyWS.MemberType MemberType, string UserName, string PassWord) {
            GlueApp.NezamMohandesyWS.GetMemberInfoByCodeRequest inValue = new GlueApp.NezamMohandesyWS.GetMemberInfoByCodeRequest();
            inValue.Body = new GlueApp.NezamMohandesyWS.GetMemberInfoByCodeRequestBody();
            inValue.Body.MeId = MeId;
            inValue.Body.MemberType = MemberType;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            GlueApp.NezamMohandesyWS.GetMemberInfoByCodeResponse retVal = ((GlueApp.NezamMohandesyWS.AccountingWebServiceSoap)(this)).GetMemberInfoByCode(inValue);
            return retVal.Body.GetMemberInfoByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetMemberInfoByCodeResponse> GlueApp.NezamMohandesyWS.AccountingWebServiceSoap.GetMemberInfoByCodeAsync(GlueApp.NezamMohandesyWS.GetMemberInfoByCodeRequest request) {
            return base.Channel.GetMemberInfoByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetMemberInfoByCodeResponse> GetMemberInfoByCodeAsync(int MeId, GlueApp.NezamMohandesyWS.MemberType MemberType, string UserName, string PassWord) {
            GlueApp.NezamMohandesyWS.GetMemberInfoByCodeRequest inValue = new GlueApp.NezamMohandesyWS.GetMemberInfoByCodeRequest();
            inValue.Body = new GlueApp.NezamMohandesyWS.GetMemberInfoByCodeRequestBody();
            inValue.Body.MeId = MeId;
            inValue.Body.MemberType = MemberType;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            return ((GlueApp.NezamMohandesyWS.AccountingWebServiceSoap)(this)).GetMemberInfoByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlueApp.NezamMohandesyWS.GetNewMembersCodeResponse GlueApp.NezamMohandesyWS.AccountingWebServiceSoap.GetNewMembersCode(GlueApp.NezamMohandesyWS.GetNewMembersCodeRequest request) {
            return base.Channel.GetNewMembersCode(request);
        }
        
        public string GetNewMembersCode(int MeId, string UserName, string PassWord) {
            GlueApp.NezamMohandesyWS.GetNewMembersCodeRequest inValue = new GlueApp.NezamMohandesyWS.GetNewMembersCodeRequest();
            inValue.Body = new GlueApp.NezamMohandesyWS.GetNewMembersCodeRequestBody();
            inValue.Body.MeId = MeId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            GlueApp.NezamMohandesyWS.GetNewMembersCodeResponse retVal = ((GlueApp.NezamMohandesyWS.AccountingWebServiceSoap)(this)).GetNewMembersCode(inValue);
            return retVal.Body.GetNewMembersCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetNewMembersCodeResponse> GlueApp.NezamMohandesyWS.AccountingWebServiceSoap.GetNewMembersCodeAsync(GlueApp.NezamMohandesyWS.GetNewMembersCodeRequest request) {
            return base.Channel.GetNewMembersCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetNewMembersCodeResponse> GetNewMembersCodeAsync(int MeId, string UserName, string PassWord) {
            GlueApp.NezamMohandesyWS.GetNewMembersCodeRequest inValue = new GlueApp.NezamMohandesyWS.GetNewMembersCodeRequest();
            inValue.Body = new GlueApp.NezamMohandesyWS.GetNewMembersCodeRequestBody();
            inValue.Body.MeId = MeId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            return ((GlueApp.NezamMohandesyWS.AccountingWebServiceSoap)(this)).GetNewMembersCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeResponse GlueApp.NezamMohandesyWS.AccountingWebServiceSoap.GetNewMembersCodeByType(GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeRequest request) {
            return base.Channel.GetNewMembersCodeByType(request);
        }
        
        public string GetNewMembersCodeByType(int MeId, GlueApp.NezamMohandesyWS.MemberType MemberType, string UserName, string PassWord) {
            GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeRequest inValue = new GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeRequest();
            inValue.Body = new GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeRequestBody();
            inValue.Body.MeId = MeId;
            inValue.Body.MemberType = MemberType;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeResponse retVal = ((GlueApp.NezamMohandesyWS.AccountingWebServiceSoap)(this)).GetNewMembersCodeByType(inValue);
            return retVal.Body.GetNewMembersCodeByTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeResponse> GlueApp.NezamMohandesyWS.AccountingWebServiceSoap.GetNewMembersCodeByTypeAsync(GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeRequest request) {
            return base.Channel.GetNewMembersCodeByTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeResponse> GetNewMembersCodeByTypeAsync(int MeId, GlueApp.NezamMohandesyWS.MemberType MemberType, string UserName, string PassWord) {
            GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeRequest inValue = new GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeRequest();
            inValue.Body = new GlueApp.NezamMohandesyWS.GetNewMembersCodeByTypeRequestBody();
            inValue.Body.MeId = MeId;
            inValue.Body.MemberType = MemberType;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            return ((GlueApp.NezamMohandesyWS.AccountingWebServiceSoap)(this)).GetNewMembersCodeByTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlueApp.NezamMohandesyWS.GetProjectInfoResponse GlueApp.NezamMohandesyWS.AccountingWebServiceSoap.GetProjectInfo(GlueApp.NezamMohandesyWS.GetProjectInfoRequest request) {
            return base.Channel.GetProjectInfo(request);
        }
        
        public string GetProjectInfo(int ProjectId, string UserName, string PassWord) {
            GlueApp.NezamMohandesyWS.GetProjectInfoRequest inValue = new GlueApp.NezamMohandesyWS.GetProjectInfoRequest();
            inValue.Body = new GlueApp.NezamMohandesyWS.GetProjectInfoRequestBody();
            inValue.Body.ProjectId = ProjectId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            GlueApp.NezamMohandesyWS.GetProjectInfoResponse retVal = ((GlueApp.NezamMohandesyWS.AccountingWebServiceSoap)(this)).GetProjectInfo(inValue);
            return retVal.Body.GetProjectInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetProjectInfoResponse> GlueApp.NezamMohandesyWS.AccountingWebServiceSoap.GetProjectInfoAsync(GlueApp.NezamMohandesyWS.GetProjectInfoRequest request) {
            return base.Channel.GetProjectInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetProjectInfoResponse> GetProjectInfoAsync(int ProjectId, string UserName, string PassWord) {
            GlueApp.NezamMohandesyWS.GetProjectInfoRequest inValue = new GlueApp.NezamMohandesyWS.GetProjectInfoRequest();
            inValue.Body = new GlueApp.NezamMohandesyWS.GetProjectInfoRequestBody();
            inValue.Body.ProjectId = ProjectId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            return ((GlueApp.NezamMohandesyWS.AccountingWebServiceSoap)(this)).GetProjectInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlueApp.NezamMohandesyWS.GetNewProjectsCodeResponse GlueApp.NezamMohandesyWS.AccountingWebServiceSoap.GetNewProjectsCode(GlueApp.NezamMohandesyWS.GetNewProjectsCodeRequest request) {
            return base.Channel.GetNewProjectsCode(request);
        }
        
        public string GetNewProjectsCode(int ProjectCode, int AgentId, string UserName, string PassWord) {
            GlueApp.NezamMohandesyWS.GetNewProjectsCodeRequest inValue = new GlueApp.NezamMohandesyWS.GetNewProjectsCodeRequest();
            inValue.Body = new GlueApp.NezamMohandesyWS.GetNewProjectsCodeRequestBody();
            inValue.Body.ProjectCode = ProjectCode;
            inValue.Body.AgentId = AgentId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            GlueApp.NezamMohandesyWS.GetNewProjectsCodeResponse retVal = ((GlueApp.NezamMohandesyWS.AccountingWebServiceSoap)(this)).GetNewProjectsCode(inValue);
            return retVal.Body.GetNewProjectsCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetNewProjectsCodeResponse> GlueApp.NezamMohandesyWS.AccountingWebServiceSoap.GetNewProjectsCodeAsync(GlueApp.NezamMohandesyWS.GetNewProjectsCodeRequest request) {
            return base.Channel.GetNewProjectsCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetNewProjectsCodeResponse> GetNewProjectsCodeAsync(int ProjectCode, int AgentId, string UserName, string PassWord) {
            GlueApp.NezamMohandesyWS.GetNewProjectsCodeRequest inValue = new GlueApp.NezamMohandesyWS.GetNewProjectsCodeRequest();
            inValue.Body = new GlueApp.NezamMohandesyWS.GetNewProjectsCodeRequestBody();
            inValue.Body.ProjectCode = ProjectCode;
            inValue.Body.AgentId = AgentId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            return ((GlueApp.NezamMohandesyWS.AccountingWebServiceSoap)(this)).GetNewProjectsCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlueApp.NezamMohandesyWS.GetCoInfoByCodeResponse GlueApp.NezamMohandesyWS.AccountingWebServiceSoap.GetCoInfoByCode(GlueApp.NezamMohandesyWS.GetCoInfoByCodeRequest request) {
            return base.Channel.GetCoInfoByCode(request);
        }
        
        public string GetCoInfoByCode(int OfficeId, string UserName, string PassWord) {
            GlueApp.NezamMohandesyWS.GetCoInfoByCodeRequest inValue = new GlueApp.NezamMohandesyWS.GetCoInfoByCodeRequest();
            inValue.Body = new GlueApp.NezamMohandesyWS.GetCoInfoByCodeRequestBody();
            inValue.Body.OfficeId = OfficeId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            GlueApp.NezamMohandesyWS.GetCoInfoByCodeResponse retVal = ((GlueApp.NezamMohandesyWS.AccountingWebServiceSoap)(this)).GetCoInfoByCode(inValue);
            return retVal.Body.GetCoInfoByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetCoInfoByCodeResponse> GlueApp.NezamMohandesyWS.AccountingWebServiceSoap.GetCoInfoByCodeAsync(GlueApp.NezamMohandesyWS.GetCoInfoByCodeRequest request) {
            return base.Channel.GetCoInfoByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetCoInfoByCodeResponse> GetCoInfoByCodeAsync(int OfficeId, string UserName, string PassWord) {
            GlueApp.NezamMohandesyWS.GetCoInfoByCodeRequest inValue = new GlueApp.NezamMohandesyWS.GetCoInfoByCodeRequest();
            inValue.Body = new GlueApp.NezamMohandesyWS.GetCoInfoByCodeRequestBody();
            inValue.Body.OfficeId = OfficeId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            return ((GlueApp.NezamMohandesyWS.AccountingWebServiceSoap)(this)).GetCoInfoByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlueApp.NezamMohandesyWS.GetNewCoCodeResponse GlueApp.NezamMohandesyWS.AccountingWebServiceSoap.GetNewCoCode(GlueApp.NezamMohandesyWS.GetNewCoCodeRequest request) {
            return base.Channel.GetNewCoCode(request);
        }
        
        public string GetNewCoCode(int OfficeId, string UserName, string PassWord) {
            GlueApp.NezamMohandesyWS.GetNewCoCodeRequest inValue = new GlueApp.NezamMohandesyWS.GetNewCoCodeRequest();
            inValue.Body = new GlueApp.NezamMohandesyWS.GetNewCoCodeRequestBody();
            inValue.Body.OfficeId = OfficeId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            GlueApp.NezamMohandesyWS.GetNewCoCodeResponse retVal = ((GlueApp.NezamMohandesyWS.AccountingWebServiceSoap)(this)).GetNewCoCode(inValue);
            return retVal.Body.GetNewCoCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetNewCoCodeResponse> GlueApp.NezamMohandesyWS.AccountingWebServiceSoap.GetNewCoCodeAsync(GlueApp.NezamMohandesyWS.GetNewCoCodeRequest request) {
            return base.Channel.GetNewCoCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlueApp.NezamMohandesyWS.GetNewCoCodeResponse> GetNewCoCodeAsync(int OfficeId, string UserName, string PassWord) {
            GlueApp.NezamMohandesyWS.GetNewCoCodeRequest inValue = new GlueApp.NezamMohandesyWS.GetNewCoCodeRequest();
            inValue.Body = new GlueApp.NezamMohandesyWS.GetNewCoCodeRequestBody();
            inValue.Body.OfficeId = OfficeId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            return ((GlueApp.NezamMohandesyWS.AccountingWebServiceSoap)(this)).GetNewCoCodeAsync(inValue);
        }
    }
}
