//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApp.accountingwebservice {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberType", Namespace="http://www.fceo.ir/")]
    public enum MemberType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Temporary = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Permanent = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.fceo.ir/", ConfigurationName="accountingwebservice.AccountingWebServiceSoap")]
    public interface AccountingWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.fceo.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetMemberInfoByCode", ReplyAction="*")]
        testApp.accountingwebservice.GetMemberInfoByCodeResponse GetMemberInfoByCode(testApp.accountingwebservice.GetMemberInfoByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetMemberInfoByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<testApp.accountingwebservice.GetMemberInfoByCodeResponse> GetMemberInfoByCodeAsync(testApp.accountingwebservice.GetMemberInfoByCodeRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.fceo.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewMembersCode", ReplyAction="*")]
        testApp.accountingwebservice.GetNewMembersCodeResponse GetNewMembersCode(testApp.accountingwebservice.GetNewMembersCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewMembersCode", ReplyAction="*")]
        System.Threading.Tasks.Task<testApp.accountingwebservice.GetNewMembersCodeResponse> GetNewMembersCodeAsync(testApp.accountingwebservice.GetNewMembersCodeRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.fceo.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewMembersCodeByType", ReplyAction="*")]
        testApp.accountingwebservice.GetNewMembersCodeByTypeResponse GetNewMembersCodeByType(testApp.accountingwebservice.GetNewMembersCodeByTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewMembersCodeByType", ReplyAction="*")]
        System.Threading.Tasks.Task<testApp.accountingwebservice.GetNewMembersCodeByTypeResponse> GetNewMembersCodeByTypeAsync(testApp.accountingwebservice.GetNewMembersCodeByTypeRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.fceo.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetProjectInfo", ReplyAction="*")]
        testApp.accountingwebservice.GetProjectInfoResponse GetProjectInfo(testApp.accountingwebservice.GetProjectInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetProjectInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<testApp.accountingwebservice.GetProjectInfoResponse> GetProjectInfoAsync(testApp.accountingwebservice.GetProjectInfoRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.fceo.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewProjectsCode", ReplyAction="*")]
        testApp.accountingwebservice.GetNewProjectsCodeResponse GetNewProjectsCode(testApp.accountingwebservice.GetNewProjectsCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewProjectsCode", ReplyAction="*")]
        System.Threading.Tasks.Task<testApp.accountingwebservice.GetNewProjectsCodeResponse> GetNewProjectsCodeAsync(testApp.accountingwebservice.GetNewProjectsCodeRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.fceo.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetCoInfoByCode", ReplyAction="*")]
        testApp.accountingwebservice.GetCoInfoByCodeResponse GetCoInfoByCode(testApp.accountingwebservice.GetCoInfoByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetCoInfoByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<testApp.accountingwebservice.GetCoInfoByCodeResponse> GetCoInfoByCodeAsync(testApp.accountingwebservice.GetCoInfoByCodeRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.fceo.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewCoCode", ReplyAction="*")]
        testApp.accountingwebservice.GetNewCoCodeResponse GetNewCoCode(testApp.accountingwebservice.GetNewCoCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fceo.ir/GetNewCoCode", ReplyAction="*")]
        System.Threading.Tasks.Task<testApp.accountingwebservice.GetNewCoCodeResponse> GetNewCoCodeAsync(testApp.accountingwebservice.GetNewCoCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberInfoByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberInfoByCode", Namespace="http://www.fceo.ir/", Order=0)]
        public testApp.accountingwebservice.GetMemberInfoByCodeRequestBody Body;
        
        public GetMemberInfoByCodeRequest() {
        }
        
        public GetMemberInfoByCodeRequest(testApp.accountingwebservice.GetMemberInfoByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetMemberInfoByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public testApp.accountingwebservice.MemberType MemberType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PassWord;
        
        public GetMemberInfoByCodeRequestBody() {
        }
        
        public GetMemberInfoByCodeRequestBody(int MeId, testApp.accountingwebservice.MemberType MemberType, string UserName, string PassWord) {
            this.MeId = MeId;
            this.MemberType = MemberType;
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberInfoByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberInfoByCodeResponse", Namespace="http://www.fceo.ir/", Order=0)]
        public testApp.accountingwebservice.GetMemberInfoByCodeResponseBody Body;
        
        public GetMemberInfoByCodeResponse() {
        }
        
        public GetMemberInfoByCodeResponse(testApp.accountingwebservice.GetMemberInfoByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetMemberInfoByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMemberInfoByCodeResult;
        
        public GetMemberInfoByCodeResponseBody() {
        }
        
        public GetMemberInfoByCodeResponseBody(string GetMemberInfoByCodeResult) {
            this.GetMemberInfoByCodeResult = GetMemberInfoByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewMembersCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewMembersCode", Namespace="http://www.fceo.ir/", Order=0)]
        public testApp.accountingwebservice.GetNewMembersCodeRequestBody Body;
        
        public GetNewMembersCodeRequest() {
        }
        
        public GetNewMembersCodeRequest(testApp.accountingwebservice.GetNewMembersCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewMembersCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        public GetNewMembersCodeRequestBody() {
        }
        
        public GetNewMembersCodeRequestBody(int MeId, string UserName, string PassWord) {
            this.MeId = MeId;
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewMembersCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewMembersCodeResponse", Namespace="http://www.fceo.ir/", Order=0)]
        public testApp.accountingwebservice.GetNewMembersCodeResponseBody Body;
        
        public GetNewMembersCodeResponse() {
        }
        
        public GetNewMembersCodeResponse(testApp.accountingwebservice.GetNewMembersCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewMembersCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNewMembersCodeResult;
        
        public GetNewMembersCodeResponseBody() {
        }
        
        public GetNewMembersCodeResponseBody(string GetNewMembersCodeResult) {
            this.GetNewMembersCodeResult = GetNewMembersCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewMembersCodeByTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewMembersCodeByType", Namespace="http://www.fceo.ir/", Order=0)]
        public testApp.accountingwebservice.GetNewMembersCodeByTypeRequestBody Body;
        
        public GetNewMembersCodeByTypeRequest() {
        }
        
        public GetNewMembersCodeByTypeRequest(testApp.accountingwebservice.GetNewMembersCodeByTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewMembersCodeByTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public testApp.accountingwebservice.MemberType MemberType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PassWord;
        
        public GetNewMembersCodeByTypeRequestBody() {
        }
        
        public GetNewMembersCodeByTypeRequestBody(int MeId, testApp.accountingwebservice.MemberType MemberType, string UserName, string PassWord) {
            this.MeId = MeId;
            this.MemberType = MemberType;
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewMembersCodeByTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewMembersCodeByTypeResponse", Namespace="http://www.fceo.ir/", Order=0)]
        public testApp.accountingwebservice.GetNewMembersCodeByTypeResponseBody Body;
        
        public GetNewMembersCodeByTypeResponse() {
        }
        
        public GetNewMembersCodeByTypeResponse(testApp.accountingwebservice.GetNewMembersCodeByTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewMembersCodeByTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNewMembersCodeByTypeResult;
        
        public GetNewMembersCodeByTypeResponseBody() {
        }
        
        public GetNewMembersCodeByTypeResponseBody(string GetNewMembersCodeByTypeResult) {
            this.GetNewMembersCodeByTypeResult = GetNewMembersCodeByTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectInfo", Namespace="http://www.fceo.ir/", Order=0)]
        public testApp.accountingwebservice.GetProjectInfoRequestBody Body;
        
        public GetProjectInfoRequest() {
        }
        
        public GetProjectInfoRequest(testApp.accountingwebservice.GetProjectInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetProjectInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProjectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        public GetProjectInfoRequestBody() {
        }
        
        public GetProjectInfoRequestBody(int ProjectId, string UserName, string PassWord) {
            this.ProjectId = ProjectId;
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectInfoResponse", Namespace="http://www.fceo.ir/", Order=0)]
        public testApp.accountingwebservice.GetProjectInfoResponseBody Body;
        
        public GetProjectInfoResponse() {
        }
        
        public GetProjectInfoResponse(testApp.accountingwebservice.GetProjectInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetProjectInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetProjectInfoResult;
        
        public GetProjectInfoResponseBody() {
        }
        
        public GetProjectInfoResponseBody(string GetProjectInfoResult) {
            this.GetProjectInfoResult = GetProjectInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewProjectsCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewProjectsCode", Namespace="http://www.fceo.ir/", Order=0)]
        public testApp.accountingwebservice.GetNewProjectsCodeRequestBody Body;
        
        public GetNewProjectsCodeRequest() {
        }
        
        public GetNewProjectsCodeRequest(testApp.accountingwebservice.GetNewProjectsCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewProjectsCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProjectCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int AgentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PassWord;
        
        public GetNewProjectsCodeRequestBody() {
        }
        
        public GetNewProjectsCodeRequestBody(int ProjectCode, int AgentId, string UserName, string PassWord) {
            this.ProjectCode = ProjectCode;
            this.AgentId = AgentId;
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewProjectsCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewProjectsCodeResponse", Namespace="http://www.fceo.ir/", Order=0)]
        public testApp.accountingwebservice.GetNewProjectsCodeResponseBody Body;
        
        public GetNewProjectsCodeResponse() {
        }
        
        public GetNewProjectsCodeResponse(testApp.accountingwebservice.GetNewProjectsCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewProjectsCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNewProjectsCodeResult;
        
        public GetNewProjectsCodeResponseBody() {
        }
        
        public GetNewProjectsCodeResponseBody(string GetNewProjectsCodeResult) {
            this.GetNewProjectsCodeResult = GetNewProjectsCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCoInfoByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCoInfoByCode", Namespace="http://www.fceo.ir/", Order=0)]
        public testApp.accountingwebservice.GetCoInfoByCodeRequestBody Body;
        
        public GetCoInfoByCodeRequest() {
        }
        
        public GetCoInfoByCodeRequest(testApp.accountingwebservice.GetCoInfoByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetCoInfoByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int OfficeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        public GetCoInfoByCodeRequestBody() {
        }
        
        public GetCoInfoByCodeRequestBody(int OfficeId, string UserName, string PassWord) {
            this.OfficeId = OfficeId;
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCoInfoByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCoInfoByCodeResponse", Namespace="http://www.fceo.ir/", Order=0)]
        public testApp.accountingwebservice.GetCoInfoByCodeResponseBody Body;
        
        public GetCoInfoByCodeResponse() {
        }
        
        public GetCoInfoByCodeResponse(testApp.accountingwebservice.GetCoInfoByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetCoInfoByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCoInfoByCodeResult;
        
        public GetCoInfoByCodeResponseBody() {
        }
        
        public GetCoInfoByCodeResponseBody(string GetCoInfoByCodeResult) {
            this.GetCoInfoByCodeResult = GetCoInfoByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewCoCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewCoCode", Namespace="http://www.fceo.ir/", Order=0)]
        public testApp.accountingwebservice.GetNewCoCodeRequestBody Body;
        
        public GetNewCoCodeRequest() {
        }
        
        public GetNewCoCodeRequest(testApp.accountingwebservice.GetNewCoCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewCoCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int OfficeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        public GetNewCoCodeRequestBody() {
        }
        
        public GetNewCoCodeRequestBody(int OfficeId, string UserName, string PassWord) {
            this.OfficeId = OfficeId;
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewCoCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewCoCodeResponse", Namespace="http://www.fceo.ir/", Order=0)]
        public testApp.accountingwebservice.GetNewCoCodeResponseBody Body;
        
        public GetNewCoCodeResponse() {
        }
        
        public GetNewCoCodeResponse(testApp.accountingwebservice.GetNewCoCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.fceo.ir/")]
    public partial class GetNewCoCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNewCoCodeResult;
        
        public GetNewCoCodeResponseBody() {
        }
        
        public GetNewCoCodeResponseBody(string GetNewCoCodeResult) {
            this.GetNewCoCodeResult = GetNewCoCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountingWebServiceSoapChannel : testApp.accountingwebservice.AccountingWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountingWebServiceSoapClient : System.ServiceModel.ClientBase<testApp.accountingwebservice.AccountingWebServiceSoap>, testApp.accountingwebservice.AccountingWebServiceSoap {
        
        public AccountingWebServiceSoapClient() {
        }
        
        public AccountingWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountingWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testApp.accountingwebservice.GetMemberInfoByCodeResponse testApp.accountingwebservice.AccountingWebServiceSoap.GetMemberInfoByCode(testApp.accountingwebservice.GetMemberInfoByCodeRequest request) {
            return base.Channel.GetMemberInfoByCode(request);
        }
        
        public string GetMemberInfoByCode(int MeId, testApp.accountingwebservice.MemberType MemberType, string UserName, string PassWord) {
            testApp.accountingwebservice.GetMemberInfoByCodeRequest inValue = new testApp.accountingwebservice.GetMemberInfoByCodeRequest();
            inValue.Body = new testApp.accountingwebservice.GetMemberInfoByCodeRequestBody();
            inValue.Body.MeId = MeId;
            inValue.Body.MemberType = MemberType;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            testApp.accountingwebservice.GetMemberInfoByCodeResponse retVal = ((testApp.accountingwebservice.AccountingWebServiceSoap)(this)).GetMemberInfoByCode(inValue);
            return retVal.Body.GetMemberInfoByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testApp.accountingwebservice.GetMemberInfoByCodeResponse> testApp.accountingwebservice.AccountingWebServiceSoap.GetMemberInfoByCodeAsync(testApp.accountingwebservice.GetMemberInfoByCodeRequest request) {
            return base.Channel.GetMemberInfoByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<testApp.accountingwebservice.GetMemberInfoByCodeResponse> GetMemberInfoByCodeAsync(int MeId, testApp.accountingwebservice.MemberType MemberType, string UserName, string PassWord) {
            testApp.accountingwebservice.GetMemberInfoByCodeRequest inValue = new testApp.accountingwebservice.GetMemberInfoByCodeRequest();
            inValue.Body = new testApp.accountingwebservice.GetMemberInfoByCodeRequestBody();
            inValue.Body.MeId = MeId;
            inValue.Body.MemberType = MemberType;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            return ((testApp.accountingwebservice.AccountingWebServiceSoap)(this)).GetMemberInfoByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testApp.accountingwebservice.GetNewMembersCodeResponse testApp.accountingwebservice.AccountingWebServiceSoap.GetNewMembersCode(testApp.accountingwebservice.GetNewMembersCodeRequest request) {
            return base.Channel.GetNewMembersCode(request);
        }
        
        public string GetNewMembersCode(int MeId, string UserName, string PassWord) {
            testApp.accountingwebservice.GetNewMembersCodeRequest inValue = new testApp.accountingwebservice.GetNewMembersCodeRequest();
            inValue.Body = new testApp.accountingwebservice.GetNewMembersCodeRequestBody();
            inValue.Body.MeId = MeId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            testApp.accountingwebservice.GetNewMembersCodeResponse retVal = ((testApp.accountingwebservice.AccountingWebServiceSoap)(this)).GetNewMembersCode(inValue);
            return retVal.Body.GetNewMembersCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testApp.accountingwebservice.GetNewMembersCodeResponse> testApp.accountingwebservice.AccountingWebServiceSoap.GetNewMembersCodeAsync(testApp.accountingwebservice.GetNewMembersCodeRequest request) {
            return base.Channel.GetNewMembersCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<testApp.accountingwebservice.GetNewMembersCodeResponse> GetNewMembersCodeAsync(int MeId, string UserName, string PassWord) {
            testApp.accountingwebservice.GetNewMembersCodeRequest inValue = new testApp.accountingwebservice.GetNewMembersCodeRequest();
            inValue.Body = new testApp.accountingwebservice.GetNewMembersCodeRequestBody();
            inValue.Body.MeId = MeId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            return ((testApp.accountingwebservice.AccountingWebServiceSoap)(this)).GetNewMembersCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testApp.accountingwebservice.GetNewMembersCodeByTypeResponse testApp.accountingwebservice.AccountingWebServiceSoap.GetNewMembersCodeByType(testApp.accountingwebservice.GetNewMembersCodeByTypeRequest request) {
            return base.Channel.GetNewMembersCodeByType(request);
        }
        
        public string GetNewMembersCodeByType(int MeId, testApp.accountingwebservice.MemberType MemberType, string UserName, string PassWord) {
            testApp.accountingwebservice.GetNewMembersCodeByTypeRequest inValue = new testApp.accountingwebservice.GetNewMembersCodeByTypeRequest();
            inValue.Body = new testApp.accountingwebservice.GetNewMembersCodeByTypeRequestBody();
            inValue.Body.MeId = MeId;
            inValue.Body.MemberType = MemberType;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            testApp.accountingwebservice.GetNewMembersCodeByTypeResponse retVal = ((testApp.accountingwebservice.AccountingWebServiceSoap)(this)).GetNewMembersCodeByType(inValue);
            return retVal.Body.GetNewMembersCodeByTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testApp.accountingwebservice.GetNewMembersCodeByTypeResponse> testApp.accountingwebservice.AccountingWebServiceSoap.GetNewMembersCodeByTypeAsync(testApp.accountingwebservice.GetNewMembersCodeByTypeRequest request) {
            return base.Channel.GetNewMembersCodeByTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<testApp.accountingwebservice.GetNewMembersCodeByTypeResponse> GetNewMembersCodeByTypeAsync(int MeId, testApp.accountingwebservice.MemberType MemberType, string UserName, string PassWord) {
            testApp.accountingwebservice.GetNewMembersCodeByTypeRequest inValue = new testApp.accountingwebservice.GetNewMembersCodeByTypeRequest();
            inValue.Body = new testApp.accountingwebservice.GetNewMembersCodeByTypeRequestBody();
            inValue.Body.MeId = MeId;
            inValue.Body.MemberType = MemberType;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            return ((testApp.accountingwebservice.AccountingWebServiceSoap)(this)).GetNewMembersCodeByTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testApp.accountingwebservice.GetProjectInfoResponse testApp.accountingwebservice.AccountingWebServiceSoap.GetProjectInfo(testApp.accountingwebservice.GetProjectInfoRequest request) {
            return base.Channel.GetProjectInfo(request);
        }
        
        public string GetProjectInfo(int ProjectId, string UserName, string PassWord) {
            testApp.accountingwebservice.GetProjectInfoRequest inValue = new testApp.accountingwebservice.GetProjectInfoRequest();
            inValue.Body = new testApp.accountingwebservice.GetProjectInfoRequestBody();
            inValue.Body.ProjectId = ProjectId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            testApp.accountingwebservice.GetProjectInfoResponse retVal = ((testApp.accountingwebservice.AccountingWebServiceSoap)(this)).GetProjectInfo(inValue);
            return retVal.Body.GetProjectInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testApp.accountingwebservice.GetProjectInfoResponse> testApp.accountingwebservice.AccountingWebServiceSoap.GetProjectInfoAsync(testApp.accountingwebservice.GetProjectInfoRequest request) {
            return base.Channel.GetProjectInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<testApp.accountingwebservice.GetProjectInfoResponse> GetProjectInfoAsync(int ProjectId, string UserName, string PassWord) {
            testApp.accountingwebservice.GetProjectInfoRequest inValue = new testApp.accountingwebservice.GetProjectInfoRequest();
            inValue.Body = new testApp.accountingwebservice.GetProjectInfoRequestBody();
            inValue.Body.ProjectId = ProjectId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            return ((testApp.accountingwebservice.AccountingWebServiceSoap)(this)).GetProjectInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testApp.accountingwebservice.GetNewProjectsCodeResponse testApp.accountingwebservice.AccountingWebServiceSoap.GetNewProjectsCode(testApp.accountingwebservice.GetNewProjectsCodeRequest request) {
            return base.Channel.GetNewProjectsCode(request);
        }
        
        public string GetNewProjectsCode(int ProjectCode, int AgentId, string UserName, string PassWord) {
            testApp.accountingwebservice.GetNewProjectsCodeRequest inValue = new testApp.accountingwebservice.GetNewProjectsCodeRequest();
            inValue.Body = new testApp.accountingwebservice.GetNewProjectsCodeRequestBody();
            inValue.Body.ProjectCode = ProjectCode;
            inValue.Body.AgentId = AgentId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            testApp.accountingwebservice.GetNewProjectsCodeResponse retVal = ((testApp.accountingwebservice.AccountingWebServiceSoap)(this)).GetNewProjectsCode(inValue);
            return retVal.Body.GetNewProjectsCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testApp.accountingwebservice.GetNewProjectsCodeResponse> testApp.accountingwebservice.AccountingWebServiceSoap.GetNewProjectsCodeAsync(testApp.accountingwebservice.GetNewProjectsCodeRequest request) {
            return base.Channel.GetNewProjectsCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<testApp.accountingwebservice.GetNewProjectsCodeResponse> GetNewProjectsCodeAsync(int ProjectCode, int AgentId, string UserName, string PassWord) {
            testApp.accountingwebservice.GetNewProjectsCodeRequest inValue = new testApp.accountingwebservice.GetNewProjectsCodeRequest();
            inValue.Body = new testApp.accountingwebservice.GetNewProjectsCodeRequestBody();
            inValue.Body.ProjectCode = ProjectCode;
            inValue.Body.AgentId = AgentId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            return ((testApp.accountingwebservice.AccountingWebServiceSoap)(this)).GetNewProjectsCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testApp.accountingwebservice.GetCoInfoByCodeResponse testApp.accountingwebservice.AccountingWebServiceSoap.GetCoInfoByCode(testApp.accountingwebservice.GetCoInfoByCodeRequest request) {
            return base.Channel.GetCoInfoByCode(request);
        }
        
        public string GetCoInfoByCode(int OfficeId, string UserName, string PassWord) {
            testApp.accountingwebservice.GetCoInfoByCodeRequest inValue = new testApp.accountingwebservice.GetCoInfoByCodeRequest();
            inValue.Body = new testApp.accountingwebservice.GetCoInfoByCodeRequestBody();
            inValue.Body.OfficeId = OfficeId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            testApp.accountingwebservice.GetCoInfoByCodeResponse retVal = ((testApp.accountingwebservice.AccountingWebServiceSoap)(this)).GetCoInfoByCode(inValue);
            return retVal.Body.GetCoInfoByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testApp.accountingwebservice.GetCoInfoByCodeResponse> testApp.accountingwebservice.AccountingWebServiceSoap.GetCoInfoByCodeAsync(testApp.accountingwebservice.GetCoInfoByCodeRequest request) {
            return base.Channel.GetCoInfoByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<testApp.accountingwebservice.GetCoInfoByCodeResponse> GetCoInfoByCodeAsync(int OfficeId, string UserName, string PassWord) {
            testApp.accountingwebservice.GetCoInfoByCodeRequest inValue = new testApp.accountingwebservice.GetCoInfoByCodeRequest();
            inValue.Body = new testApp.accountingwebservice.GetCoInfoByCodeRequestBody();
            inValue.Body.OfficeId = OfficeId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            return ((testApp.accountingwebservice.AccountingWebServiceSoap)(this)).GetCoInfoByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testApp.accountingwebservice.GetNewCoCodeResponse testApp.accountingwebservice.AccountingWebServiceSoap.GetNewCoCode(testApp.accountingwebservice.GetNewCoCodeRequest request) {
            return base.Channel.GetNewCoCode(request);
        }
        
        public string GetNewCoCode(int OfficeId, string UserName, string PassWord) {
            testApp.accountingwebservice.GetNewCoCodeRequest inValue = new testApp.accountingwebservice.GetNewCoCodeRequest();
            inValue.Body = new testApp.accountingwebservice.GetNewCoCodeRequestBody();
            inValue.Body.OfficeId = OfficeId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            testApp.accountingwebservice.GetNewCoCodeResponse retVal = ((testApp.accountingwebservice.AccountingWebServiceSoap)(this)).GetNewCoCode(inValue);
            return retVal.Body.GetNewCoCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testApp.accountingwebservice.GetNewCoCodeResponse> testApp.accountingwebservice.AccountingWebServiceSoap.GetNewCoCodeAsync(testApp.accountingwebservice.GetNewCoCodeRequest request) {
            return base.Channel.GetNewCoCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<testApp.accountingwebservice.GetNewCoCodeResponse> GetNewCoCodeAsync(int OfficeId, string UserName, string PassWord) {
            testApp.accountingwebservice.GetNewCoCodeRequest inValue = new testApp.accountingwebservice.GetNewCoCodeRequest();
            inValue.Body = new testApp.accountingwebservice.GetNewCoCodeRequestBody();
            inValue.Body.OfficeId = OfficeId;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            return ((testApp.accountingwebservice.AccountingWebServiceSoap)(this)).GetNewCoCodeAsync(inValue);
        }
    }
}
